import { AchievementDef } from '../types/game';

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'depth_500',
    title: '破光潛航 (Dusk Descent)',
    desc: '下潛深度首次超過 500 米，進入黃昏沉船帶。',
    icon: '🧭',
    rewardText: '+100 珍珠',
    category: 'depth',
  },
  {
    id: 'depth_1000',
    title: '千米深淵探索者 (1,000m Pioneer)',
    desc: '首次深潛突破 1,000 米午夜海溝，直面深海高壓！',
    icon: '🌊',
    rewardText: '+300 珍珠 · +1 星石',
    category: 'depth',
  },
  {
    id: 'depth_2000',
    title: '無光深溝極客 (Abyssal Venturer)',
    desc: '潛入超過 2,000 米極限高壓無光深溝。',
    icon: '⚓',
    rewardText: '+800 珍珠 · +2 星石',
    category: 'depth',
  },
  {
    id: 'depth_3000',
    title: '極限星核征服者 (Hadal Conqueror)',
    desc: '深入超過 3,000 米深淵星核，探索無底幽海！',
    icon: '👑',
    rewardText: '+2,000 珍珠 · +5 星石',
    category: 'depth',
  },
  {
    id: 'pearls_1000',
    title: '珍珠水手 (Pearl Diver)',
    desc: '生涯累計獲得超過 1,000 顆珍珠。',
    icon: '💰',
    rewardText: '+150 珍珠',
    category: 'wealth',
  },
  {
    id: 'pearls_10000',
    title: '萬珠大亨 (Millionaire Turtle)',
    desc: '生涯累計獲得超過 10,000 顆珍珠！富甲深海！',
    icon: '🏆',
    rewardText: '+1,500 珍珠 · +3 星石',
    category: 'wealth',
  },
  {
    id: 'crystals_5',
    title: '星石初現 (Starlight Spark)',
    desc: '累計開採獲得 5 顆稀有星石晶體 💠。',
    icon: '💠',
    rewardText: '+200 珍珠',
    category: 'mining',
  },
  {
    id: 'crystals_20',
    title: '星河晶簇收藏家 (Cosmic Geode)',
    desc: '累計開採獲得 20 顆稀有星石晶體 💠！',
    icon: '🔮',
    rewardText: '+1,000 珍珠 · +2 星石',
    category: 'mining',
  },
  {
    id: 'upgrade_3',
    title: '機體改裝學者 (Mod Specialist)',
    desc: '在母艦天賦樹中累計升級 3 次科技節點。',
    icon: '⚡',
    rewardText: '+150 珍珠',
    category: 'tech',
  },
  {
    id: 'tech_drone',
    title: '自動化時代 (Autonomous Partner)',
    desc: '成功解鎖自律採集水母無人機夥伴！',
    icon: '🤖',
    rewardText: '+500 珍珠 · +2 星石',
    category: 'tech',
  },
  {
    id: 'dive_5',
    title: '深海老舵手 (Seasoned Captain)',
    desc: '累計完成 5 次深海探險與歸航。',
    icon: '🎖️',
    rewardText: '+300 珍珠',
    category: 'depth',
  },
];
