import { TalentNode } from '../types/game';

export const INITIAL_TALENTS: TalentNode[] = [
  // --- 1. 生存與機動分支 (Survival & Mobility) ---
  {
    id: 'o2_tank',
    name: '巨大化氣瓶',
    desc: '提高最大氧氣容量 +35 秒，能在深海停留更久',
    category: 'survival',
    max: 5,
    lvl: 0,
    cost: (l) => [100, 250, 600, 1500, 3500][l] ?? 3500,
    cur: 'pearls',
    x: 130,
    y: 110,
    req: [],
  },
  {
    id: 'fins',
    name: '超導推進尾鰭',
    desc: '海龜水中遊動速度提升 +25%',
    category: 'survival',
    max: 4,
    lvl: 0,
    cost: (l) => [80, 220, 500, 1200][l] ?? 1200,
    cur: 'pearls',
    x: 270,
    y: 110,
    req: ['o2_tank'],
  },
  {
    id: 'pressure_hull',
    name: '抗壓合金龜殼',
    desc: '大幅降低深海高水壓下的耗氧速率 (-25% 每級)',
    category: 'survival',
    max: 3,
    lvl: 0,
    cost: (l) => [220, 750, 2200][l] ?? 2200,
    cur: 'pearls',
    x: 130,
    y: 230,
    req: ['o2_tank'],
  },
  {
    id: 'emergency_boost',
    name: '緊急逃生噴射氣閥',
    desc: '當氧氣低於 20% 時，游速自動暴增 40% 協助火速返航',
    category: 'survival',
    max: 2,
    lvl: 0,
    cost: (l) => [3, 8][l] ?? 8,
    cur: 'crystals',
    x: 270,
    y: 230,
    req: ['pressure_hull', 'fins'],
  },

  // --- 2. 採集與雷射矩陣 (Laser Matrix) ---
  {
    id: 'laser_power',
    name: '高頻採集光束',
    desc: '增加雷射每秒採礦傷害 +50%',
    category: 'laser',
    max: 5,
    lvl: 0,
    cost: (l) => [120, 300, 750, 1800, 4200][l] ?? 4200,
    cur: 'pearls',
    x: 470,
    y: 110,
    req: [],
  },
  {
    id: 'laser_range',
    name: '聚能折射稜鏡',
    desc: '增加雷射光束照射距離 +35%',
    category: 'laser',
    max: 3,
    lvl: 0,
    cost: (l) => [150, 400, 1000][l] ?? 1000,
    cur: 'pearls',
    x: 610,
    y: 110,
    req: ['laser_power'],
  },
  {
    id: 'disintegrate',
    name: '分子裂解科技',
    desc: '拆解沉船礦物有機率額外崩解出星石晶體 💠',
    category: 'laser',
    max: 3,
    lvl: 0,
    cost: (l) => [2, 6, 14][l] ?? 14,
    cur: 'crystals',
    x: 470,
    y: 230,
    req: ['laser_power'],
  },
  {
    id: 'dual_laser',
    name: '雙聯共振光束',
    desc: '激發雙重平行雷射光束，大幅增加掃描拆解判定面積',
    category: 'laser',
    max: 1,
    lvl: 0,
    cost: (l) => [10][l] ?? 10,
    cur: 'crystals',
    x: 610,
    y: 230,
    req: ['laser_range', 'disintegrate'],
  },

  // --- 3. 貨艙與深海經濟 (Cargo & Economics) ---
  {
    id: 'cargo_bay',
    name: '次元海藻背包',
    desc: '增加背包負重上限 +12 空間',
    category: 'cargo',
    max: 5,
    lvl: 0,
    cost: (l) => [90, 250, 650, 1600, 4000][l] ?? 4000,
    cur: 'pearls',
    x: 810,
    y: 110,
    req: [],
  },
  {
    id: 'magnet',
    name: '渦流磁吸力場',
    desc: '自動將一定範圍內的掉落珍珠與星石吸向海龜身邊',
    category: 'cargo',
    max: 3,
    lvl: 0,
    cost: (l) => [180, 550, 1400][l] ?? 1400,
    cur: 'pearls',
    x: 810,
    y: 230,
    req: ['cargo_bay'],
  },
  {
    id: 'pearl_alchemy',
    name: '珍珠共鳴質變',
    desc: '水母販售收益增加 +35%（每級累積疊加）',
    category: 'cargo',
    max: 4,
    lvl: 0,
    cost: (l) => [150, 400, 1000, 2500][l] ?? 2500,
    cur: 'pearls',
    x: 950,
    y: 170,
    req: ['cargo_bay'],
  },

  // --- 4. 終極高階科技 (Tech & Drone) ---
  {
    id: 'drone',
    name: '自律採集水母無人機',
    desc: '召喚一隻小無人機伴隨左右，自動雷射拆解周圍礦石',
    category: 'tech',
    max: 1,
    lvl: 0,
    cost: (l) => [15][l] ?? 15,
    cur: 'crystals',
    x: 470,
    y: 350,
    req: ['disintegrate', 'pressure_hull'],
  },
  {
    id: 'depth_sight',
    name: '深淵生物雷達',
    desc: '在視野邊緣標註稀有高價值黃金水母與星石礦簇方向',
    category: 'tech',
    max: 1,
    lvl: 0,
    cost: (l) => [8][l] ?? 8,
    cur: 'crystals',
    x: 650,
    y: 350,
    req: ['disintegrate'],
  },
];
